"""Central pytest classification and Task 4 necessity audit metadata.

Every behavior test file is registered explicitly. Resource flags are audit evidence
only; no layer/domain is inferred dynamically from source text.
"""
from __future__ import annotations

PRIMARY_LAYERS = {"unit", "contract", "integration"}
ORTHOGONAL_MARKERS = {"smoke", "slow", "serial"}
DOMAIN_MARKERS = {"base", "runtime", "workflow", "cards", "knowledge", "wiki", "autonomy", "roles", "migration", "release", "portability"}
NECESSITY_CLASSES = {"KEEP_INDEPENDENT_CONTRACT", "KEEP_REGRESSION", "MERGE_CANDIDATE", "SUPERSEDED_CANDIDATE"}
_RESOURCE_NAMES = ("subprocess", "sqlite", "git", "network", "port", "shared_temp", "env_mutation", "cwd_mutation")

def _case(layer: str, domains: tuple[str, ...], necessity: str, main_contracts: str, *, resources: tuple[str, ...] = (), parallel: str = "YES", slow: bool = False, serial: bool = False) -> dict:
    resource_set = set(resources)
    unknown = resource_set - set(_RESOURCE_NAMES)
    if unknown:
        raise ValueError(f"unknown test resource flags: {sorted(unknown)}")
    return {
        "layer": layer,
        "domains": domains,
        "necessity": necessity,
        "parallel_candidate": parallel,
        "resources": {name: name in resource_set for name in _RESOURCE_NAMES},
        "main_contracts": main_contracts,
        "slow": slow,
        "serial": serial,
    }

TEST_FILE_CATALOG = {
    'scripts/tests/test_v532_browser_reports.py': _case('integration', ('runtime', 'base'), 'KEEP_INDEPENDENT_CONTRACT', 'native Playwright outcome mapping, opt-in bounded attachment custody, evidence replay and no automatic visual PASS', resources=('subprocess', 'sqlite', 'git', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/test_v532_project_surface.py': _case('integration', ('base', 'portability'), 'KEEP_INDEPENDENT_CONTRACT', 'production project sync preserves owned bytes and rejects ambiguous markers/symlink writes', resources=('subprocess', 'sqlite', 'git', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/test_v532_cli_contract.py': _case('integration', ('runtime', 'cards', 'base'), 'KEEP_INDEPENDENT_CONTRACT', 'production zero-card lifecycle, CLI timing/correlation/failure and content-fresh config', resources=('subprocess', 'sqlite', 'git', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/test_v532_recording.py': _case('integration', ('runtime', 'base'), 'KEEP_INDEPENDENT_CONTRACT', 'logical request receipt replay/conflict/concurrency, automatic copied artifact binding and configured limits', resources=('subprocess', 'sqlite', 'git', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/test_v532_waiting.py': _case('integration', ('runtime', 'workflow'), 'KEEP_INDEPENDENT_CONTRACT', 'typed waits, owner/dependency resolution and unchanged prerequisite rejection', resources=('subprocess', 'sqlite', 'git', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/test_v532_projection_resilience.py': _case('integration', ('runtime', 'base'), 'KEEP_INDEPENDENT_CONTRACT', 'optional continuation recovery without rolling back facts; required projections and terminal seal remain atomic', resources=('subprocess', 'sqlite', 'git', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/migration/test_v523_to_v524_role_map.py': _case('contract', ('migration', 'roles'), 'KEEP_REGRESSION', 'v523 to v524 role map regression/compatibility contract'),
    'scripts/tests/test_b12_structured_refs.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'b12 structured refs regression/compatibility contract'),
    'scripts/tests/test_b14_lossless_summary.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'b14 lossless summary regression/compatibility contract'),
    'scripts/tests/test_b17_regression.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'b17 regression regression/compatibility contract'),
    'scripts/tests/test_b18_cutover_rehearsal.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'b18 cutover rehearsal regression/compatibility contract'),
    'scripts/tests/test_c1_review_preflight.py': _case('integration', ('base',), 'KEEP_REGRESSION', 'c1 review preflight regression/compatibility contract', resources=('subprocess', 'git')),
    'scripts/tests/test_c5_s1_validator.py': _case('integration', ('base',), 'KEEP_REGRESSION', 'c5 s1 validator regression/compatibility contract', resources=('subprocess', 'git')),
    'scripts/tests/test_card_workflow_semantics.py': _case('integration', ('cards', 'workflow'), 'KEEP_INDEPENDENT_CONTRACT', 'workflow step, execution-role, conditional-role, terminal and rework presentation semantics', resources=('sqlite', 'env_mutation')),
    'scripts/tests/test_config_loader.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'governance/config parser validation, error codes, and supported success paths'),
    'scripts/tests/test_test_suite_governance.py': _case('contract', ('release', 'base'), 'KEEP_INDEPENDENT_CONTRACT', 'pytest catalog completeness, marker taxonomy, fail-closed classification, and coverage mapping'),
    'scripts/tests/test_v510_active_contract.py': _case('integration', ('base',), 'KEEP_REGRESSION', 'v510 active contract regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v510_runtime_defaults.py': _case('contract', ('runtime',), 'KEEP_REGRESSION', 'v510 runtime defaults regression/compatibility contract'),
    'scripts/tests/test_v510_version_purity.py': _case('contract', ('release',), 'KEEP_REGRESSION', 'v510 version purity regression/compatibility contract', resources=('subprocess',)),
    'scripts/tests/test_v511_encoding.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'v511 encoding regression/compatibility contract'),
    'scripts/tests/test_v511_external_repair.py': _case('integration', ('base',), 'KEEP_REGRESSION', 'v511 external repair regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v511_frontmatter.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'v511 frontmatter regression/compatibility contract'),
    'scripts/tests/test_v511_template_completeness.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'v511 template completeness regression/compatibility contract'),
    'scripts/tests/test_v512_integrated_upgrade.py': _case('integration', ('migration',), 'KEEP_REGRESSION', 'v512 integrated upgrade regression/compatibility contract', resources=('subprocess', 'sqlite', 'git')),
    'scripts/tests/test_v512_maintenance.py': _case('integration', ('base',), 'KEEP_REGRESSION', 'v512 maintenance regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v513_base_convergence.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'v513 base convergence regression/compatibility contract'),
    'scripts/tests/test_v513_knowledge_standardization.py': _case('integration', ('knowledge',), 'KEEP_REGRESSION', 'v513 knowledge standardization regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v513_portability.py': _case('integration', ('portability',), 'KEEP_REGRESSION', 'v513 portability regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v513_record_first.py': _case('integration', ('runtime',), 'KEEP_REGRESSION', 'v513 record first regression/compatibility contract', resources=('subprocess', 'sqlite', 'git')),
    'scripts/tests/test_v513_runtime_portability.py': _case('integration', ('runtime', 'portability'), 'KEEP_REGRESSION', 'v513 runtime portability regression/compatibility contract', resources=('sqlite', 'env_mutation')),
    'scripts/tests/test_v513_skill_semantics.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'v513 skill semantics regression/compatibility contract'),
    'scripts/tests/test_v513_wiki_standardization.py': _case('contract', ('wiki',), 'KEEP_REGRESSION', 'v513 wiki standardization regression/compatibility contract'),
    'scripts/tests/test_v514_orchestration_adversarial.py': _case('integration', ('workflow',), 'KEEP_REGRESSION', 'v514 orchestration adversarial regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v514_orchestration_contract.py': _case('contract', ('workflow',), 'KEEP_REGRESSION', 'v514 orchestration contract regression/compatibility contract'),
    'scripts/tests/test_v514_orchestration_integration.py': _case('integration', ('workflow',), 'KEEP_REGRESSION', 'v514 orchestration integration regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v514_orchestration_router.py': _case('integration', ('workflow',), 'KEEP_REGRESSION', 'orchestration level routing, stage routing, and review/rework role decisions', resources=('sqlite',)),
    'scripts/tests/test_v514_release_convergence.py': _case('contract', ('release',), 'KEEP_REGRESSION', 'v514 release convergence regression/compatibility contract'),
    'scripts/tests/test_v514_risk_escalation.py': _case('integration', ('workflow',), 'KEEP_REGRESSION', 'v514 risk escalation regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v514_upgrade.py': _case('contract', ('migration',), 'KEEP_REGRESSION', 'v514 upgrade regression/compatibility contract'),
    'scripts/tests/test_v520_final_convergence.py': _case('integration', ('release',), 'KEEP_REGRESSION', 'v520 final convergence regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v520_namespace_migration.py': _case('contract', ('migration',), 'KEEP_REGRESSION', 'v520 namespace migration regression/compatibility contract'),
    'scripts/tests/test_v520_namespace_purity.py': _case('contract', ('release',), 'KEEP_REGRESSION', 'active namespace purity and release exclusion of process-history docs'),
    'scripts/tests/test_v520_open_source_release.py': _case('integration', ('release',), 'KEEP_REGRESSION', 'v520 open source release regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation')),
    'scripts/tests/test_v520_windows_portability.py': _case('integration', ('portability',), 'KEEP_REGRESSION', 'v520 windows portability regression/compatibility contract', resources=('subprocess', 'sqlite', 'env_mutation')),
    'scripts/tests/test_v521_project_memory.py': _case('contract', ('runtime',), 'KEEP_REGRESSION', 'v521 project memory regression/compatibility contract'),
    'scripts/tests/test_v522_context_effectiveness.py': _case('integration', ('base',), 'KEEP_REGRESSION', 'v522 context effectiveness regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v522_context_usage.py': _case('integration', ('base',), 'KEEP_REGRESSION', 'v522 context usage regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation')),
    'scripts/tests/test_v522_contracts.py': _case('contract', ('base',), 'KEEP_REGRESSION', 'v522 contracts regression/compatibility contract'),
    'scripts/tests/test_v522_wiki_namespace_anchor_recovery.py': _case('contract', ('wiki',), 'KEEP_REGRESSION', 'v522 wiki namespace anchor recovery regression/compatibility contract'),
    'scripts/tests/test_v522_workflow_delivery_hardening.py': _case('integration', ('workflow',), 'KEEP_REGRESSION', 'v522 workflow delivery hardening regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation')),
    'scripts/tests/test_v523_autonomy_batch.py': _case('integration', ('autonomy',), 'KEEP_REGRESSION', 'v523 autonomy batch regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/test_v523_autonomy_cycle_fencing.py': _case('integration', ('autonomy',), 'KEEP_REGRESSION', 'v523 autonomy cycle fencing regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation')),
    'scripts/tests/test_v523_autonomy_discovery.py': _case('integration', ('autonomy',), 'KEEP_REGRESSION', 'v523 autonomy discovery regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation')),
    'scripts/tests/test_v523_autonomy_envelope.py': _case('integration', ('autonomy',), 'KEEP_REGRESSION', 'v523 autonomy envelope regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/test_v523_autonomy_integration.py': _case('integration', ('autonomy',), 'KEEP_REGRESSION', 'v523 autonomy integration regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation', 'cwd_mutation'), slow=True),
    'scripts/tests/test_v523_autonomy_phase0_contract.py': _case('integration', ('autonomy',), 'KEEP_REGRESSION', 'v523 autonomy phase0 contract regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v523_autonomy_profile.py': _case('integration', ('autonomy',), 'KEEP_REGRESSION', 'v523 autonomy profile regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation')),
    'scripts/tests/test_v523_autonomy_release.py': _case('contract', ('autonomy',), 'KEEP_REGRESSION', 'v523 autonomy release regression/compatibility contract'),
    'scripts/tests/test_v523_autonomy_review.py': _case('integration', ('autonomy',), 'KEEP_REGRESSION', 'v523 autonomy review regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/test_v523_autonomy_workspace.py': _case('integration', ('autonomy',), 'KEEP_REGRESSION', 'v523 autonomy workspace regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation')),
    'scripts/tests/test_v523_runtime_hardening.py': _case('integration', ('runtime',), 'KEEP_REGRESSION', 'v523 runtime hardening regression/compatibility contract', resources=('sqlite', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/test_v524_contract_cutover.py': _case('contract', ('base',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 contract cutover regression/compatibility contract'),
    'scripts/tests/test_v524_delivery_knowledge_handoff.py': _case('integration', ('knowledge', 'workflow'), 'KEEP_INDEPENDENT_CONTRACT', 'v524 delivery knowledge handoff regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v524_directory_convergence.py': _case('contract', ('release',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 directory convergence regression/compatibility contract'),
    'scripts/tests/test_v524_legacy_runtime_retirement.py': _case('contract', ('runtime',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 legacy runtime retirement regression/compatibility contract'),
    'scripts/tests/test_v524_no_tail.py': _case('contract', ('release',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 no tail regression/compatibility contract'),
    'scripts/tests/test_v524_powershell_cli_first.py': _case('contract', ('release',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 powershell cli first regression/compatibility contract'),
    'scripts/tests/test_v524_product_router.py': _case('contract', ('workflow',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 product router regression/compatibility contract'),
    'scripts/tests/test_v524_requirement_ready.py': _case('contract', ('workflow',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 requirement ready regression/compatibility contract'),
    'scripts/tests/test_v524_review_isolation.py': _case('contract', ('workflow',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 review isolation regression/compatibility contract'),
    'scripts/tests/test_v524_review_locator.py': _case('unit', ('workflow',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 review locator regression/compatibility contract'),
    'scripts/tests/test_v524_role_catalog.py': _case('contract', ('roles',), 'KEEP_INDEPENDENT_CONTRACT', 'formal role catalog structure and skill-path validity'),
    'scripts/tests/test_v524_role_first_contract.py': _case('contract', ('roles',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 role first contract regression/compatibility contract'),
    'scripts/tests/test_v524_role_reference_inventory.py': _case('contract', ('roles',), 'KEEP_INDEPENDENT_CONTRACT', 'role-reference inventory classification and deterministic report payload'),
    'scripts/tests/test_v524_role_resolver.py': _case('integration', ('roles',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 role resolver regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v524_task_role_ownership.py': _case('contract', ('roles',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 task role ownership regression/compatibility contract'),
    'scripts/tests/test_v524_trusted_role_results.py': _case('contract', ('roles',), 'KEEP_INDEPENDENT_CONTRACT', 'v524 trusted role results regression/compatibility contract'),
    'scripts/tests/test_v525_markitdown_integration.py': _case('contract', ('base',), 'KEEP_INDEPENDENT_CONTRACT', 'v525 markitdown integration regression/compatibility contract'),
    'scripts/tests/test_v526_event_presentation.py': _case('contract', ('runtime', 'cards'), 'KEEP_INDEPENDENT_CONTRACT', 'v526 event presentation regression/compatibility contract'),
    'scripts/tests/test_v526_html_cards.py': _case('integration', ('cards', 'workflow'), 'KEEP_INDEPENDENT_CONTRACT', 'card snapshot/render/display artifact and refresh contracts', resources=('sqlite', 'env_mutation', 'cwd_mutation')),
    'scripts/tests/test_v526_temp_artifacts.py': _case('integration', ('runtime',), 'KEEP_INDEPENDENT_CONTRACT', 'owned execution-temp lifecycle, cleanup evidence, and delivery blocking', resources=('subprocess', 'sqlite', 'git', 'shared_temp', 'env_mutation')),
    'scripts/tests/test_v527_document_navigation.py': _case('contract', ('release',), 'KEEP_INDEPENDENT_CONTRACT', 'v527 document navigation regression/compatibility contract'),
    'scripts/tests/test_v527_skill_topology.py': _case('contract', ('roles',), 'KEEP_INDEPENDENT_CONTRACT', 'v527 skill topology regression/compatibility contract'),
    'scripts/tests/test_v529_acceptance_database.py': _case('integration', ('workflow',), 'KEEP_INDEPENDENT_CONTRACT', 'v529 acceptance database regression/compatibility contract', resources=('subprocess', 'sqlite', 'git')),
    'scripts/tests/test_v529_baseline_consistency.py': _case('integration', ('workflow',), 'KEEP_INDEPENDENT_CONTRACT', 'v529 baseline consistency regression/compatibility contract', resources=('sqlite',)),
    'scripts/tests/test_v529_change_set_binding.py': _case('integration', ('runtime',), 'KEEP_INDEPENDENT_CONTRACT', 'Change Set digest/binding and stale verification-review-delivery contracts', resources=('subprocess', 'git')),
    'scripts/tests/test_v529_delivery_rework.py': _case('integration', ('workflow',), 'KEEP_INDEPENDENT_CONTRACT', 'v529 delivery rework regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation'), slow=True),
    'scripts/tests/test_v529_development_habits.py': _case('contract', ('workflow',), 'KEEP_INDEPENDENT_CONTRACT', 'v529 development habits regression/compatibility contract'),
    'scripts/tests/test_v529_knowledge_convergence.py': _case('integration', ('knowledge', 'workflow'), 'KEEP_INDEPENDENT_CONTRACT', 'typed Knowledge request/result provenance, source binding, and invalidation', resources=('subprocess', 'sqlite', 'git', 'env_mutation'), slow=True),
    'scripts/tests/test_v529_migration_release.py': _case('integration', ('migration', 'release'), 'KEEP_INDEPENDENT_CONTRACT', 'v529 migration release regression/compatibility contract', resources=('subprocess', 'sqlite', 'git')),
    'scripts/tests/test_v529_terminal_projection.py': _case('integration', ('runtime',), 'KEEP_INDEPENDENT_CONTRACT', 'v529 terminal projection regression/compatibility contract', resources=('subprocess', 'sqlite', 'git', 'env_mutation')),
    'scripts/tests/test_v529_visual_verification.py': _case('integration', ('workflow', 'cards'), 'KEEP_INDEPENDENT_CONTRACT', 'visual evidence manifest and temporary-auth cleanup delivery gates', resources=('subprocess', 'sqlite', 'git', 'shared_temp', 'env_mutation'), slow=True),
    'scripts/tests/test_v531_graphify_no_go.py': _case('contract', ('release',), 'KEEP_INDEPENDENT_CONTRACT', 'Graphify M2 No-Go decision, no-runtime-dependency boundary, and release-note traceability'),
    'scripts/tests/test_v531_requirement_frontier.py': _case('contract', ('workflow', 'roles'), 'KEEP_INDEPENDENT_CONTRACT', 'conditional Requirement Frontier ordering, fact/decision separation, convergence, and no-new-runtime boundary'),
}

SMOKE_NODEIDS = {
    'scripts/tests/test_config_loader.py::TestSuccessPaths::test_all_governance_validate',
    'scripts/tests/test_v510_active_contract.py::TestActiveContract::test_gate_accepts_active_version',
    'scripts/tests/test_v513_record_first.py::RecordFirstCase::test_simple_verified_flow_has_small_event_budget',
    'scripts/tests/test_v514_orchestration_router.py::test_l1_on_demand_route_and_explicit_architecture',
    'scripts/tests/test_v524_role_catalog.py::test_catalog_has_only_new_active_role_model',
    'scripts/tests/test_v526_html_cards.py::test_renderer_contains_core_fields_interactions_and_snapshot_notice',
}

COVERAGE_MAPPINGS = (
    {
        'old_nodeid': 'scripts/tests/test_v524_role_reference_inventory.py::test_removed_role_inventory_is_not_shipped',
        'replacement_nodeid': 'scripts/tests/test_v520_namespace_purity.py::test_process_history_docs_are_not_shipped',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'docs/history process-history artifacts are not shipped',
        'evidence': 'AST-normalized bodies are identical',
        'decision': 'DELETE_EXACT_DUPLICATE',
    },
    {
        'old_nodeid': 'scripts/tests/test_v510_agent_contracts.py::TestAgentContracts::test_all_skills_version_511',
        'replacement_nodeid': 'scripts/tests/test_v524_role_catalog.py::test_catalog_has_only_new_active_role_model',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'all catalog-declared role skills use the active version',
        'evidence': 'canonical role-catalog validator checks every role Skill frontmatter version',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v510_agent_contracts.py::TestAgentContracts::test_no_legacy_template_path_in_skills',
        'replacement_nodeid': 'scripts/tests/test_v524_role_catalog.py::test_catalog_has_only_new_active_role_model',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'catalog-declared role skills do not contain the retired template/version token',
        'evidence': 'canonical role-catalog test now scans every declared role Skill for the retired token',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v510_agent_contracts.py::TestAgentContracts::test_role_catalog_hashes_match',
        'replacement_nodeid': 'scripts/tests/test_v524_role_catalog.py::test_catalog_has_only_new_active_role_model',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'role-catalog content_sha256 matches normalized Skill content',
        'evidence': 'canonical role-catalog test invokes update_role_catalog.validate, which checks every content_sha256',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v510_agent_contracts.py::TestAgentContracts::test_role_catalog_version_511',
        'replacement_nodeid': 'scripts/tests/test_v524_role_catalog.py::test_catalog_has_only_new_active_role_model',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'role-catalog catalog_version/base_version match VERSION',
        'evidence': 'canonical role-catalog validator checks both version fields',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v510_version_purity.py::TestVersionPurity::test_no_legacy_dirs',
        'replacement_nodeid': 'scripts/tests/test_v520_open_source_release.py::test_only_active_task_template_contract_is_shipped',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'only the active template directory is shipped and cutover-snapshots is absent',
        'evidence': 'release-surface test retains the exact directory assertion and now also checks cutover-snapshots absence',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v511_agent_contracts.py::TestRoleCatalog::test_catalog_has_expected_roles_and_hashes',
        'replacement_nodeid': 'scripts/tests/test_v524_role_catalog.py::test_catalog_has_only_new_active_role_model',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'active role set, catalog version, skill existence and hashes are valid',
        'evidence': 'canonical role-catalog test asserts the exact role set and invokes the stronger validator',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v511_agent_contracts.py::TestAgentSkills::test_agent_versions',
        'replacement_nodeid': 'scripts/tests/test_v524_role_catalog.py::test_catalog_has_only_new_active_role_model',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'every catalog-declared role Skill uses active VERSION',
        'evidence': 'canonical role-catalog validator checks every declared role Skill version',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v511_agent_contracts.py::TestAgentSkills::test_requirement_analysis_is_pretask_and_low_bookkeeping',
        'replacement_nodeid': 'scripts/tests/test_v513_skill_semantics.py::TestWorkflowRoleSemantics::test_requirement_keeps_fact_assumption_decision_boundary',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'requirement role keeps pre-task and low-bookkeeping boundaries',
        'evidence': 'all original semantic anchors and the max_search_rounds rejection were folded into the canonical requirement-role test',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v511_agent_contracts.py::TestAgentSkills::test_architecture_review_is_risk_triggered_not_default_gate',
        'replacement_nodeid': 'scripts/tests/test_v513_skill_semantics.py::TestWorkflowRoleSemantics::test_architecture_review_is_compact_but_professional',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'architecture review is risk-triggered and not a mandatory L2/L3 gate',
        'evidence': 'all original positive/negative anchors were folded into the canonical architecture-review semantic test',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v511_agent_contracts.py::TestAgentSkills::test_roles_do_business_not_projection_bookkeeping',
        'replacement_nodeid': 'scripts/tests/test_v513_skill_semantics.py::TestWorkflowRoleSemantics::test_compact_roles_still_reject_old_daily_bookkeeping',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'roles avoid stage-handoff bookkeeping while preserving test/delivery ownership boundaries',
        'evidence': 'stage-handoff checks plus test-complete and Delivery Result anchors are retained in canonical skill-semantic tests',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v511_agent_contracts.py::TestCostTiering::test_l0_l3_are_risk_labels_not_fixed_expensive_flows',
        'replacement_nodeid': 'scripts/tests/test_v513_record_first.py::RecordFirstCase::test_public_workflow_is_small_and_phases_are_facts',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'L0-L3 use NEW-ACTIVE-COMPLETED and architecture review is optional by default',
        'evidence': 'replacement contains the same assertions on all four levels and architecture_review.default',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v513_record_first.py::TestRecordFirstStaticContracts::test_optional_templates_have_no_stage_handoff',
        'replacement_nodeid': 'scripts/tests/test_v511_template_completeness.py::TestTemplateCompleteness::test_upgraded_templates_reference_v511_artifacts',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'optional business templates do not contain stage_handoff',
        'evidence': 'replacement iterates the same template set and adds task/readme contract assertions',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v513_skill_semantics.py::TestRoleCatalogMetadata::test_catalog_metadata_matches_skill_frontmatter',
        'replacement_nodeid': 'scripts/tests/test_v524_role_catalog.py::test_catalog_has_only_new_active_role_model',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'role-catalog id/type/version metadata matches Skill frontmatter',
        'evidence': 'canonical role-catalog validator checks id, type and version for every declared Skill',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v520_open_source_release.py::test_version_purity_scanner_rejects_previous_minor_after_v520_cutover',
        'replacement_nodeid': 'scripts/tests/test_v510_version_purity.py::TestVersionPurity::test_scanner_rejects_previous_patch',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'version-purity scanner rejects older same-major dotted versions',
        'evidence': 'canonical scanner regression now covers old patch, old minor and immediate prior-minor samples',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v524_delivery_knowledge_handoff.py::test_legacy_task_scoped_knowledge_handoff_is_rejected',
        'replacement_nodeid': 'scripts/tests/test_v522_contracts.py::test_legacy_task_scoped_knowledge_fast_paths_are_retired',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'legacy task-scoped Knowledge handoff is rejected',
        'evidence': 'replacement exercises the same empty payload plus an additional reusable-finding legacy payload',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v524_release_docs.py::test_readme_exposes_current_entry_and_document_map',
        'replacement_nodeid': 'scripts/tests/test_v520_open_source_release.py::test_readme_explains_value_quickstart_agents_and_portability',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'README exposes current entry/model and hides retired workflow-orchestrator',
        'evidence': 'all original README assertions were folded into the broader canonical README release-surface test',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v524_release_docs.py::test_getting_started_links_back_to_ai_install_entry_and_current_model',
        'replacement_nodeid': 'scripts/tests/test_v520_open_source_release.py::test_getting_started_supports_ai_assisted_clean_machine_setup',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'GETTING_STARTED links to install entry/current model and avoids retired workflow/re-init guidance',
        'evidence': 'all original GETTING_STARTED anchors were folded into the canonical onboarding test',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v524_release_docs.py::test_agents_and_skills_is_current_model_not_migration_history',
        'replacement_nodeid': 'scripts/tests/test_v520_open_source_release.py::test_development_flow_has_one_external_lead_and_three_independent_agents',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'AGENTS_AND_SKILLS documents the current role model and no retired Action Role history',
        'evidence': 'original documentation assertions were folded into the canonical public role-surface test',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v524_release_docs.py::test_changelog_keeps_release_history_not_process_plan',
        'replacement_nodeid': 'scripts/tests/test_v520_open_source_release.py::test_public_brand_and_release_version',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'CHANGELOG retains current release/navigation history',
        'evidence': 'original CHANGELOG anchors were folded into the canonical public release identity test',
        'decision': 'DELETE_CONSOLIDATED_CONTRACT',
    },
    {
        'old_nodeid': 'scripts/tests/test_v524_role_catalog.py::test_subskill_paths_are_real',
        'replacement_nodeid': 'scripts/tests/test_v524_role_catalog.py::test_catalog_has_only_new_active_role_model',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'declared subskill ids/paths resolve to valid capability Skills',
        'evidence': 'update_role_catalog.validate checks subskill metadata, path prefix, existence, frontmatter identity/version and mode',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v527_document_navigation.py::test_document_navigation_checker_exists',
        'replacement_nodeid': 'scripts/tests/test_v527_document_navigation.py::test_public_document_navigation_has_no_broken_links_or_process_paths',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'document-navigation checker exists and is loadable',
        'evidence': 'replacement loads the checker module before validating the live documentation surface',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v527_document_navigation.py::test_current_document_entrypoints_exist',
        'replacement_nodeid': 'scripts/tests/test_v527_document_navigation.py::test_public_document_navigation_has_no_broken_links_or_process_paths',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'core public document entrypoints exist',
        'evidence': 'validate_document_navigation checks every CORE_DOCUMENTS entrypoint before link validation',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v527_document_navigation.py::test_generated_agent_topology_blocks_match_catalog',
        'replacement_nodeid': 'scripts/tests/test_v527_document_navigation.py::test_public_document_navigation_has_no_broken_links_or_process_paths',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'generated Agent topology blocks match role catalog',
        'evidence': 'validate_document_navigation includes validate_agent_guides and generated docs Agent-map verification',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v527_document_navigation.py::test_process_document_release_surface_is_removed',
        'replacement_nodeid': 'scripts/tests/test_v527_document_navigation.py::test_public_document_navigation_has_no_broken_links_or_process_paths',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'retired process-document files are absent',
        'evidence': 'validate_document_navigation calls retired_process_files and reports every retired process file',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v522_workflow_delivery_hardening.py::V522WorkflowDeliveryCase::test_ready_delivery_without_knowledge_signal_needs_no_knowledge_effect',
        'replacement_nodeid': 'scripts/tests/test_v529_knowledge_convergence.py::test_no_knowledge_signal_is_not_required',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'delivery without a Knowledge signal emits no convergence request and can complete',
        'evidence': 'typed Knowledge replacement checks no request plus task_complete/complete routing',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v522_workflow_delivery_hardening.py::V522WorkflowDeliveryCase::test_new_verification_invalidates_old_delivery_result',
        'replacement_nodeid': 'scripts/tests/test_v529_delivery_rework.py::V529ChangeSetWorkflowCase::test_reverification_requires_fresh_code_review_before_delivery',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'a newer Verification invalidates the old Review/Delivery chain until a fresh Code Review exists',
        'evidence': 'change-set-aware replacement rejects Delivery after re-verification and now asserts fresh Review restores Delivery routing',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
    {
        'old_nodeid': 'scripts/tests/test_v522_workflow_delivery_hardening.py::V522WorkflowDeliveryCase::test_required_knowledge_convergence_blocks_completion_until_result',
        'replacement_nodeid': 'scripts/tests/test_v529_knowledge_convergence.py::test_required_request_without_result_routes_knowledge_and_blocks_completion',
        'classification': 'SUPERSEDED_CANDIDATE',
        'protected_contract': 'required typed Knowledge convergence blocks completion until a valid Result clears the effect',
        'evidence': 'replacement validates Request binding/dispatch/blocking and now records NO_DURABLE_INSIGHT before asserting task_complete',
        'decision': 'DELETE_STRICT_SUPERSET',
    },
)

# Static-string overlap groups are audit candidates only; no deletion is authorized without node-level coverage evidence.
OVERLAP_REVIEW_GROUPS = (
    {
        'classification': 'MERGE_CANDIDATE',
        'name': 'agent/skill contracts',
        'paths': ('scripts/tests/test_v513_skill_semantics.py', 'scripts/tests/test_v522_contracts.py', 'scripts/tests/test_v527_skill_topology.py'),
        'decision': 'KEEP_DISTINCT_AFTER_NODE_LEVEL_AUDIT',
    },
    {
        'classification': 'MERGE_CANDIDATE',
        'name': 'release/purity/navigation',
        'paths': ('scripts/tests/test_v510_version_purity.py', 'scripts/tests/test_v520_namespace_purity.py', 'scripts/tests/test_v520_open_source_release.py', 'scripts/tests/test_v527_document_navigation.py'),
        'decision': 'KEEP_DISTINCT_AFTER_NODE_LEVEL_AUDIT',
    },
    {
        'classification': 'MERGE_CANDIDATE',
        'name': 'role static contracts',
        'paths': ('scripts/tests/test_v524_role_catalog.py', 'scripts/tests/test_v524_role_first_contract.py', 'scripts/tests/test_v524_role_reference_inventory.py', 'scripts/tests/test_v527_skill_topology.py', 'scripts/tests/test_v529_baseline_consistency.py'),
        'decision': 'KEEP_PENDING_NODE_LEVEL_MAPPING',
    },
)

def metadata_for_path(path: str) -> dict:
    """Return registered metadata or fail closed for a newly added test file."""
    try:
        return TEST_FILE_CATALOG[path]
    except KeyError as exc:
        raise KeyError(f"unregistered test file: {path}") from exc
